language: python
sudo: true
services:
  - docker
branches:
  only:
    - gh-pages
    - /^.*$/
install:
  - pip install -e .
  - pip install nose
script:
  - nosetests
  - if [ $TRAVIS_BRANCH == "gh-pages" or $TRAVIS_PULL_REQUEST ]; then
    estep validate -v --resolve;
    else
    estep validate -v;
    fi
  - docker run --rm --volume=$(pwd):/srv/jekyll jekyll/jekyll:pages jekyll build
cache: pip
