language: python
sudo: true
branches:
  only:
    - gh-pages
    - /^.*$/
install:
  - pip install -e .
  - pip install nose
  - gem install github-pages
script:
  - nosetests
  - if [ $TRAVIS_BRANCH == "gh-pages" -o -v $TRAVIS_PULL_REQUEST ]; then
    estep validate -v --resolve;
    else
    estep validate -v;
    fi
  - jekyll build
cache: 
  - pip
  - bundler
