language: python
branches:
  only:
    - gh-pages
    - /^.*$/
install:
  - pip install -e .
script:
  - python -m doctest estep/validate.py
  - if [ $TRAVIS_BRANCH == "gh-pages" ] || [ $TRAVIS_PULL_REQUEST ]; then
    estep validate -v --resolve
    else
    estep validate -v
    fi
