language: python
branches:
  only:
    - gh-pages
    - /^.*$/
install:
  - pip install -e .
script:
  - if [ $TRAVIS_BRANCH == "gh-pages" ] || [ $TRAVIS_PULL_REQUEST ]; then
    estep validate -v --resolve;
    else
    estep validate -v;
    fi

