language: python
sudo: required
services:
  - docker
cache:
  pip: true
  directories:
    - .cache/resolve
branches:
  only:
    - gh-pages
    - /^.*$/
install:
  - pip install -e .
  - pip install nose
script:
  - nosetests
  - if [ $TRAVIS_BRANCH == "gh-pages" ] || [ $TRAVIS_PULL_REQUEST ]; then
    estep validate -v --resolve;
    elif [ $TRAVIS_BRANCH == "develop" ]; then
    estep validate -v --local;
    else
    estep validate -v;
    fi
  - docker run --rm --volume=$(pwd):/srv/jekyll jekyll/jekyll:pages jekyll build
