# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: eScience Technology Platform
email: estep@esciencecenter.nl
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://estep.esciencecenter.nl" # the base hostname & protocol for your site
twitter_username: esciencecenter
github_username:  eStep

# Build settings
markdown: kramdown
collections:
  software:
    output: true
    permalink: /software/:path
defaults:
  - scope:
      path: ""
      type: software
    values:
      layout: software
