# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: eScience Technology Platform
email: estep@esciencecenter.nl
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://estep.esciencecenter.nl" # the base hostname & protocol for your site
twitter_username: esciencecenter
github_username:  eStep
json_excludes:
- next
- previous
- output
- path
- layout
- relative_path
- content  # renamed to 'description'
- url  # renamed to '@id'
- collection

# Build settings
markdown: kramdown
permalink: pretty
collections:
  software:
    output: true
  project:
    output: true
  person:
    output: true
  organization:
    output: true
defaults:
  - scope:
      path: ""
      type: software
    values:
      layout: software
      schema: http://estep.esciencecenter.nl/schema/software
  - scope:
      path: ""
      type: project
    values:
      layout: project
      schema: http://estep.esciencecenter.nl/schema/project
  - scope:
      path: ""
      type: person
    values:
      layout: person
      schema: http://estep.esciencecenter.nl/schema/person
  - scope:
      path: ""
      type: organization
    values:
      layout: organization
      schema: http://estep.esciencecenter.nl/schema/organization
